using Injectio.Generators.Extensions;
using Injectio.Generators.Infrastructure;
using Injectio.Generators.Models;

namespace Injectio.Generators;

public static class ServiceRegistrationWriter
{

    public static string GenerateExtensionClass(
        IReadOnlyList<ModuleRegistration> moduleRegistrations,
        IReadOnlyList<ServiceRegistration> serviceRegistrations,
        string? assemblyName,
        string? methodName,
        string? methodInternal)
        => GenerateExtensionClass(moduleRegistrations, serviceRegistrations, Array.Empty<DecoratorRegistration>(), assemblyName, methodName, methodInternal);

    public static string GenerateExtensionClass(
        IReadOnlyList<ModuleRegistration> moduleRegistrations,
        IReadOnlyList<ServiceRegistration> serviceRegistrations,
        IReadOnlyList<DecoratorRegistration> decoratorRegistrations,
        string? assemblyName,
        string? methodName,
        string? methodInternal)
    {
        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
            .AppendLine("namespace Microsoft.Extensions.DependencyInjection")
            .AppendLine("{")
            .IncrementIndent()
            .AppendLine("/// <summary>")
            .AppendLine("/// Extension methods for discovered service registrations")
            .AppendLine("/// </summary>");

        codeBuilder
            .AppendLine("public static class DiscoveredServicesExtensions")
            .AppendLine("{")
            .IncrementIndent()
            .AppendLine("/// <summary>")
            .AppendLine($"/// Adds discovered services from {assemblyName ?? string.Empty} to the specified service collection")
            .AppendLine("/// </summary>")
            .AppendLine("/// <param name=\"serviceCollection\">The service collection.</param>")
            .AppendLine("/// <param name=\"tags\">The service registration tags to include.</param>")
            .AppendLine("/// <returns>The service collection</returns>")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append(string.Equals(methodInternal, "true") ? "internal" : "public")
            .Append(" static global::Microsoft.Extensions.DependencyInjection.IServiceCollection")
            .Append(" Add")
            .Append(methodName ?? "InjectioService")
            .AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection, params string[]? tags)")
            .AppendLine("{")
            .IncrementIndent();


        codeBuilder
            .AppendLine("var tagSet = new global::System.Collections.Generic.HashSet<string>(tags ?? global::System.Linq.Enumerable.Empty<string>());")
            .AppendLine();

        var moduleCount = 1;

        foreach (var moduleRegistration in moduleRegistrations)
        {
            moduleCount = WriteModule(codeBuilder, moduleRegistration, moduleCount);
        }

        foreach (var serviceRegistration in serviceRegistrations)
        {
            WriteRegistration(codeBuilder, serviceRegistration);
        }

        foreach (var decoratorRegistration in decoratorRegistrations)
        {
            WriteDecorator(codeBuilder, decoratorRegistration);
        }

        codeBuilder
            .AppendLine("return serviceCollection;")
            .DecrementIndent()
            .AppendLine("}") // method
            .DecrementIndent()
            .AppendLine("}") // class
            .DecrementIndent()
            .AppendLine("}"); // namespace

        return codeBuilder.ToString();
    }

    private static int WriteModule(
        IndentedStringBuilder codeBuilder,
        ModuleRegistration moduleRegistration,
        int moduleCount)
    {
        if (moduleRegistration.IsStatic)
        {
            codeBuilder
                .AppendIf("global::", !moduleRegistration.ClassName.StartsWith("global::"))
                .Append(moduleRegistration.ClassName)
                .Append('.')
                .Append(moduleRegistration.MethodName)
                .Append("(")
                .Append("serviceCollection")
                .AppendIf(", tagSet", moduleRegistration.HasTagCollection)
                .Append(");")
                .AppendLine()
                .AppendLine();
        }
        else
        {
            codeBuilder
                .Append("var module")
                .Append($"{moduleCount:0000}")
                .Append(" = new ")
                .AppendIf("global::", !moduleRegistration.ClassName.StartsWith("global::"))
                .Append(moduleRegistration.ClassName)
                .AppendLine("();");

            codeBuilder
                .Append("module")
                .Append($"{moduleCount:0000}")
                .Append('.')
                .Append(moduleRegistration.MethodName)
                .Append("(")
                .Append("serviceCollection")
                .AppendIf(", tagSet", moduleRegistration.HasTagCollection)
                .Append(");")
                .AppendLine()
                .AppendLine();

            moduleCount++;
        }

        return moduleCount;
    }

    private static void WriteRegistration(
        IndentedStringBuilder codeBuilder,
        ServiceRegistration serviceRegistration)
    {
        if (serviceRegistration.Tags.Count > 0)
        {
            codeBuilder
                .Append("if (tagSet.Count == 0 || tagSet.Intersect(new[] { ");

            bool wroteTag = false;
            foreach (var tag in serviceRegistration.Tags)
            {
                if (wroteTag)
                    codeBuilder.Append(", ");

                codeBuilder
                    .Append("\"")
                    .Append(tag)
                    .Append("\"");

                wroteTag = true;
            }

            codeBuilder
                .AppendLine(" }).Any())")
                .AppendLine("{")
                .IncrementIndent();
        }

        var serviceMethod = GetServiceCollectionMethod(serviceRegistration.Duplicate);

        foreach (var serviceType in serviceRegistration.ServiceTypes)
        {
            if (serviceType.IsNullOrWhiteSpace())
                continue;

            if (serviceRegistration.IsOpenGeneric)
                WriteServiceType(codeBuilder, serviceRegistration, serviceMethod, serviceType);
            else
                WriteServiceGeneric(codeBuilder, serviceRegistration, serviceMethod, serviceType);
        }

        if (serviceRegistration.Tags.Count > 0)
        {
            codeBuilder
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }
    }

    private static void WriteServiceType(
        IndentedStringBuilder codeBuilder,
        ServiceRegistration serviceRegistration,
        string serviceMethod,
        string serviceType)
    {
        var describeMethod = GetServiceDescriptorMethod(serviceRegistration);

        codeBuilder
            .Append("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.")
            .Append(serviceMethod)
            .AppendLine("(")
            .IncrementIndent()
            .AppendLine("serviceCollection,")
            .Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.")
            .Append(describeMethod)
            .AppendLine("(")
            .IncrementIndent()
            .Append("typeof(")
            .AppendIf("global::", !serviceType.StartsWith("global::"))
            .Append(serviceType)
            .AppendLine("),");

        if (serviceRegistration.ServiceKey.HasValue())
        {
            codeBuilder
                .Append(serviceRegistration.ServiceKey)
                .AppendLine(",");
        }

        if (serviceRegistration.Factory.HasValue())
        {
            bool hasNamespace = serviceRegistration.Factory?.Contains(".") == true;

            codeBuilder
                .AppendIf(serviceRegistration.ImplementationType, !hasNamespace)
                .AppendIf(".", !hasNamespace)
                .Append(serviceRegistration.Factory);
        }
        else if (serviceRegistration.ImplementationType.HasValue())
        {
            codeBuilder
                .Append("typeof(")
                .AppendIf("global::", !serviceRegistration.ImplementationType.StartsWith("global::"))
                .Append(serviceRegistration.ImplementationType)
                .Append(')');
        }
        else
        {
            codeBuilder
                .Append("typeof(")
                .AppendIf("global::", !serviceType.StartsWith("global::"))
                .Append(serviceType)
                .Append(')');
        }

        codeBuilder
            .AppendLine()
            .DecrementIndent()
            .AppendLine(")")
            .DecrementIndent()
            .AppendLine(");")
            .AppendLine();
    }

    private static void WriteServiceGeneric(
        IndentedStringBuilder codeBuilder,
        ServiceRegistration serviceRegistration,
        string serviceMethod,
        string serviceType)
    {
        var describeMethod = GetServiceDescriptorMethod(serviceRegistration);

        var implementationType = serviceRegistration.ImplementationType.HasValue()
            ? serviceRegistration.ImplementationType
            : serviceType;

        codeBuilder
            .Append("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.")
            .Append(serviceMethod)
            .AppendLine("(")
            .IncrementIndent()
            .AppendLine("serviceCollection,")
            .Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.")
            .Append(describeMethod)
            .Append("<")
            .AppendIf("global::", !serviceType.StartsWith("global::"))
            .Append(serviceType);

        // don't include the implementation type if there is factory
        if (serviceRegistration.Factory.IsNullOrEmpty())
        {
            codeBuilder
                .Append(", ")
                .AppendIf("global::", !implementationType.StartsWith("global::"))
                .Append(implementationType);
        }

        codeBuilder.Append(">(");

        // write service key argument
        if (serviceRegistration.ServiceKey.HasValue())
            codeBuilder.Append(serviceRegistration.ServiceKey);

        // write factory method
        if (serviceRegistration.Factory.HasValue())
        {
            bool hasNamespace = serviceRegistration.Factory?.Contains(".") == true;

            codeBuilder
                .AppendIf(", ", serviceRegistration.ServiceKey.HasValue()) // second argument if there is a service key
                .AppendIf(serviceRegistration.ImplementationType, !hasNamespace)
                .AppendIf(".", !hasNamespace)
                .Append(serviceRegistration.Factory);
        }
        else if (serviceRegistration.Registration == KnownTypes.RegistrationStrategySelfWithProxyFactoryShortName
            && serviceRegistration.ImplementationType != serviceType)
        {
            codeBuilder
                .AppendIf(", ", serviceRegistration.ServiceKey.HasValue())
                .AppendLine()
                .IncrementIndent()
                .Append("(serviceProvider")
                .AppendIf(", key", serviceRegistration.ServiceKey.HasValue())
                .Append(") => global::Microsoft.Extensions.DependencyInjection.ServiceProvider")
                .Append(serviceRegistration.ServiceKey.HasValue()
                    ? "KeyedServiceExtensions.GetRequiredKeyedService<"
                    : "ServiceExtensions.GetRequiredService<")
                .AppendIf("global::", !serviceRegistration.ImplementationType.StartsWith("global::"))
                .Append(serviceRegistration.ImplementationType)
                .Append(">(serviceProvider")
                .AppendIf(", key", serviceRegistration.ServiceKey.HasValue())
                .Append(")")
                .AppendLine()
                .DecrementIndent();
        }

        codeBuilder
            .AppendLine(")")
            .DecrementIndent()
            .AppendLine(");")
            .AppendLine();
    }

    private static void WriteDecorator(
        IndentedStringBuilder codeBuilder,
        DecoratorRegistration decorator)
    {
        if (decorator.Tags.Count > 0)
        {
            codeBuilder
                .Append("if (tagSet.Count == 0 || tagSet.Intersect(new[] { ");

            bool wroteTag = false;
            foreach (var tag in decorator.Tags)
            {
                if (wroteTag)
                    codeBuilder.Append(", ");

                codeBuilder
                    .Append("\"")
                    .Append(tag)
                    .Append("\"");

                wroteTag = true;
            }

            codeBuilder
                .AppendLine(" }).Any())")
                .AppendLine("{")
                .IncrementIndent();
        }

        var serviceType = decorator.ServiceType;
        var decoratorType = decorator.DecoratorType;
        bool hasServiceKey = decorator.ServiceKey.HasValue();
        bool isKeyed = hasServiceKey || decorator.IsAnyKey;

        // resolve the service key expression passed to the helper
        string keyExpression;
        if (decorator.IsAnyKey)
            keyExpression = "global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey";
        else if (hasServiceKey)
            keyExpression = decorator.ServiceKey!;
        else
            keyExpression = "null";

        if (decorator.IsOpenGeneric)
        {
            codeBuilder
                .Append("global::Injectio.Extensions.DecorationExtensions.DecorateOpenGeneric(")
                .AppendLine()
                .IncrementIndent()
                .AppendLine("serviceCollection,")
                .Append("typeof(")
                .AppendIf("global::", !serviceType.StartsWith("global::"))
                .Append(serviceType)
                .AppendLine("),")
                .Append("typeof(")
                .AppendIf("global::", !decoratorType.StartsWith("global::"))
                .Append(decoratorType)
                .AppendLine(")")
                .DecrementIndent()
                .AppendLine(");")
                .AppendLine();
        }
        else if (isKeyed)
        {
            codeBuilder
                .Append("global::Injectio.Extensions.DecorationExtensions.DecorateKeyed<")
                .AppendIf("global::", !serviceType.StartsWith("global::"))
                .Append(serviceType)
                .AppendLine(">(")
                .IncrementIndent()
                .AppendLine("serviceCollection,")
                .Append(keyExpression)
                .AppendLine(",");

            WriteDecoratorFactory(codeBuilder, decorator, isKeyed: true);

            codeBuilder
                .AppendLine()
                .DecrementIndent()
                .AppendLine(");")
                .AppendLine();
        }
        else
        {
            codeBuilder
                .Append("global::Injectio.Extensions.DecorationExtensions.Decorate<")
                .AppendIf("global::", !serviceType.StartsWith("global::"))
                .Append(serviceType)
                .AppendLine(">(")
                .IncrementIndent()
                .AppendLine("serviceCollection,");

            WriteDecoratorFactory(codeBuilder, decorator, isKeyed: false);

            codeBuilder
                .AppendLine()
                .DecrementIndent()
                .AppendLine(");")
                .AppendLine();
        }

        if (decorator.Tags.Count > 0)
        {
            codeBuilder
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }
    }

    private static void WriteDecoratorFactory(
        IndentedStringBuilder codeBuilder,
        DecoratorRegistration decorator,
        bool isKeyed)
    {
        var serviceType = decorator.ServiceType;
        var decoratorType = decorator.DecoratorType;
        var qualifiedService = serviceType.StartsWith("global::") ? serviceType : "global::" + serviceType;
        var qualifiedDecorator = decoratorType.StartsWith("global::") ? decoratorType : "global::" + decoratorType;

        if (decorator.Factory.HasValue())
        {
            bool hasNamespace = decorator.Factory!.Contains(".");
            var factoryTarget = hasNamespace ? decorator.Factory! : qualifiedDecorator + "." + decorator.Factory;

            if (isKeyed)
            {
                codeBuilder
                    .Append("static (serviceProvider, serviceKey, inner) => ")
                    .Append(factoryTarget)
                    .Append("(serviceProvider, serviceKey, inner)");
            }
            else
            {
                codeBuilder
                    .Append("static (serviceProvider, inner) => ")
                    .Append(factoryTarget)
                    .Append("(serviceProvider, inner)");
            }
        }
        else
        {
            if (isKeyed)
            {
                codeBuilder
                    .Append("static (serviceProvider, serviceKey, inner) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<")
                    .Append(qualifiedDecorator)
                    .Append(">(serviceProvider, inner)");
            }
            else
            {
                codeBuilder
                    .Append("static (serviceProvider, inner) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<")
                    .Append(qualifiedDecorator)
                    .Append(">(serviceProvider, inner)");
            }
        }
    }

    public static string GetServiceCollectionMethod(string duplicateStrategy)
    {
        return duplicateStrategy switch
        {
            KnownTypes.DuplicateStrategySkipShortName => "TryAdd",
            KnownTypes.DuplicateStrategySkipTypeName => "TryAdd",
            KnownTypes.DuplicateStrategyReplaceShortName => "Replace",
            KnownTypes.DuplicateStrategyReplaceTypeName => "Replace",
            KnownTypes.DuplicateStrategyAppendShortName => "Add",
            KnownTypes.DuplicateStrategyAppendTypeName => "Add",
            _ => "TryAdd"
        };
    }

    public static string GetServiceDescriptorMethod(ServiceRegistration serviceRegistration)
    {
        var describeMethod = serviceRegistration.Lifetime switch
        {
            KnownTypes.ServiceLifetimeSingletonFullName => "Singleton",
            KnownTypes.ServiceLifetimeScopedFullName => "Scoped",
            KnownTypes.ServiceLifetimeTransientFullName => "Transient",
            _ => "Transient"
        };

        return serviceRegistration.ServiceKey.HasValue()
            ? $"Keyed{describeMethod}"
            : describeMethod;
    }
}
