// <auto-generated />
#nullable enable

namespace Injectio.Extensions;

/// <summary>
/// Provides extension methods for decorating registered services in an <see cref="global::Microsoft.Extensions.DependencyInjection.IServiceCollection"/>.
/// </summary>
/// <remarks>
/// <para>
/// The <b>Decorator pattern</b> wraps an existing service with additional behavior without modifying the
/// original implementation. Each decorator implements the same interface as the service it wraps, creating
/// a chain of responsibility:
/// </para>
/// <para>
/// These methods work by replacing the <see cref="global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor"/>
/// in-place within the service collection. The original factory, instance, or implementation type is captured
/// so the inner service can still be resolved. The replacement descriptor preserves the original lifetime.
/// Calling a decoration method multiple times stacks decorators, with the last call becoming the outermost layer.
/// </para>
/// <para><b>Usage example — decorating with a factory:</b></para>
/// <code>
/// // Register the original service
/// services.AddScoped&lt;INotificationService, EmailNotificationService&gt;();
///
/// // Decorate with logging
/// services.Decorate&lt;INotificationService&gt;(
///     (sp, inner) =&gt; new LoggingNotificationService(inner, sp.GetRequiredService&lt;ILogger&gt;()));
///
/// // Decorate with retry (stacks on top of logging)
/// services.Decorate&lt;INotificationService&gt;(
///     (sp, inner) =&gt; new RetryNotificationService(inner));
///
/// // Resolution chain: Retry → Logging → Email
/// </code>
/// <para><b>Usage example — decorating open generics:</b></para>
/// <code>
/// // Register closed-generic implementations
/// services.AddScoped&lt;IRepository&lt;Order&gt;, OrderRepository&gt;();
/// services.AddScoped&lt;IRepository&lt;Customer&gt;, CustomerRepository&gt;();
///
/// // Decorate all IRepository&lt;T&gt; with caching
/// services.DecorateOpenGeneric(
///     typeof(IRepository&lt;&gt;), typeof(CachingRepository&lt;&gt;));
/// </code>
/// </remarks>
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static class DecorationExtensions
{
    /// <summary>
    /// Decorates all registrations of <typeparamref name="TService"/> by wrapping each resolved instance with <paramref name="decoratorFactory"/>.
    /// Keyed service registrations are skipped.
    /// </summary>
    /// <typeparam name="TService">The service type to decorate.</typeparam>
    /// <param name="services">The service collection containing the registrations to decorate.</param>
    /// <param name="decoratorFactory">A factory that receives the service provider and the original instance, and returns the decorated instance.</param>
    /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
    /// <remarks>
    /// <para>
    /// Decoration replaces each existing <see cref="global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor"/> for
    /// <typeparamref name="TService"/> in-place. The original descriptor's factory, instance, or implementation type is
    /// captured and used to resolve the inner service, which is then passed to <paramref name="decoratorFactory"/>.
    /// The replacement descriptor preserves the original registration's lifetime.
    /// </para>
    /// <para>
    /// Multiple calls stack: each call wraps whatever factory is currently registered, enabling layered decoration.
    /// Only non-keyed registrations are affected; use <c>DecorateKeyed</c> for keyed services.
    /// </para>
    /// </remarks>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Decorate<TService>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Func<global::System.IServiceProvider, TService, TService> decoratorFactory)
        where TService : class
    {
        var serviceType = typeof(TService);

        for (int i = 0; i < services.Count; i++)
        {
            var descriptor = services[i];
            if (descriptor.ServiceType != serviceType)
                continue;

            if (IsKeyedDescriptor(descriptor))
                continue;

            var inner = CreateInnerFactory(descriptor);
            var lifetime = descriptor.Lifetime;

            services[i] = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                serviceType: serviceType,
                factory: sp => decoratorFactory(sp, (TService)inner(sp))!,
                lifetime: lifetime
            );
        }

        return services;
    }

    /// <summary>
    /// Decorates all registrations of <typeparamref name="TService"/> by wrapping each resolved instance
    /// with an automatically constructed instance of <typeparamref name="TDecorator"/>.
    /// Keyed service registrations are skipped.
    /// </summary>
    /// <typeparam name="TService">The service type to decorate.</typeparam>
    /// <typeparam name="TDecorator">The decorator type. Its constructor must accept a <typeparamref name="TService"/> parameter for the inner service; additional parameters are resolved from the service provider.</typeparam>
    /// <param name="services">The service collection containing the registrations to decorate.</param>
    /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
    /// <remarks>
    /// <para>
    /// This overload uses <see cref="global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance"/>
    /// to construct the decorator, passing the inner service instance as an explicit argument. Any remaining
    /// constructor parameters are resolved from the <see cref="global::System.IServiceProvider"/>.
    /// </para>
    /// </remarks>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Decorate<TService, TDecorator>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TService : class
        where TDecorator : class, TService
    {
        return services.Decorate<TService>(
            (sp, inner) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<TDecorator>(sp, inner));
    }

#if NET8_0_OR_GREATER
    /// <summary>
    /// Decorates all keyed registrations of <typeparamref name="TService"/> matching <paramref name="serviceKey"/>
    /// by wrapping each resolved instance with <paramref name="decoratorFactory"/>.
    /// Pass <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> to match all keys.
    /// </summary>
    /// <typeparam name="TService">The service type to decorate.</typeparam>
    /// <param name="services">The service collection containing the registrations to decorate.</param>
    /// <param name="serviceKey">The key to match, or <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> for all keys.</param>
    /// <param name="decoratorFactory">A factory that receives the service provider, the key, and the original instance, and returns the decorated instance.</param>
    /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
    /// <remarks>
    /// <para>
    /// This method iterates through all service descriptors for <typeparamref name="TService"/> and replaces each
    /// keyed registration whose key matches <paramref name="serviceKey"/>. The original keyed factory, instance,
    /// or implementation type is captured and used to resolve the inner service, which is then passed to
    /// <paramref name="decoratorFactory"/> along with the service provider and key. The replacement descriptor
    /// preserves the original registration's lifetime and key.
    /// </para>
    /// <para>
    /// Non-keyed registrations are skipped; use <c>Decorate</c> for those. Multiple calls stack, enabling
    /// layered decoration of keyed services.
    /// </para>
    /// </remarks>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateKeyed<TService>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        object? serviceKey,
        global::System.Func<global::System.IServiceProvider, object?, TService, TService> decoratorFactory)
        where TService : class
    {
        var serviceType = typeof(TService);
        bool anyKey = ReferenceEquals(serviceKey, global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey);

        for (int i = 0; i < services.Count; i++)
        {
            var descriptor = services[i];
            if (descriptor.ServiceType != serviceType)
                continue;

            if (!descriptor.IsKeyedService)
                continue;

            if (!anyKey && !global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(descriptor.ServiceKey, serviceKey))
                continue;

            var originalKey = descriptor.ServiceKey;
            var innerKeyed = CreateInnerKeyedFactory(descriptor);
            var lifetime = descriptor.Lifetime;

            services[i] = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                serviceType: serviceType,
                serviceKey: originalKey,
                factory: (sp, key) => decoratorFactory(sp, key, (TService)innerKeyed(sp, key))!,
                lifetime: lifetime);
        }

        return services;
    }

    /// <summary>
    /// Decorates all keyed registrations of <typeparamref name="TService"/> matching <paramref name="serviceKey"/>
    /// by wrapping each resolved instance with an automatically constructed instance of <typeparamref name="TDecorator"/>.
    /// Pass <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> to match all keys.
    /// </summary>
    /// <typeparam name="TService">The service type to decorate.</typeparam>
    /// <typeparam name="TDecorator">The decorator type. Its constructor must accept a <typeparamref name="TService"/> parameter for the inner service; additional parameters are resolved from the service provider.</typeparam>
    /// <param name="services">The service collection containing the registrations to decorate.</param>
    /// <param name="serviceKey">The key to match, or <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> for all keys.</param>
    /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
    /// <remarks>
    /// <para>
    /// This overload uses <see cref="global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance"/>
    /// to construct the decorator, passing the inner service instance as an explicit argument. Any remaining
    /// constructor parameters are resolved from the <see cref="global::System.IServiceProvider"/>.
    /// </para>
    /// </remarks>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateKeyed<TService, TDecorator>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        object? serviceKey)
        where TService : class
        where TDecorator : class, TService
    {
        return services.DecorateKeyed<TService>(
            serviceKey,
            (sp, key, inner) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<TDecorator>(sp, inner));
    }
#endif

    /// <summary>
    /// Decorates all closed-generic registrations whose generic type definition matches <paramref name="openServiceType"/>
    /// by wrapping each resolved instance with an instance of <paramref name="openDecoratorType"/>.
    /// </summary>
    /// <param name="services">The service collection containing the registrations to decorate.</param>
    /// <param name="openServiceType">The open generic service type (e.g., <c>typeof(IRepository&lt;&gt;)</c>).</param>
    /// <param name="openDecoratorType">The open generic decorator type that wraps the original service.</param>
    /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
    /// <remarks>
    /// <para>
    /// This method scans all service descriptors for closed-generic types whose generic type definition matches
    /// <paramref name="openServiceType"/>. For each match, it closes <paramref name="openDecoratorType"/> over the
    /// same type arguments and replaces the descriptor with a factory that resolves the original service and passes
    /// it to <see cref="global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance"/>.
    /// The replacement descriptor preserves the original registration's lifetime.
    /// </para>
    /// <para>
    /// Open-generic descriptors (those registered with an open <c>typeof(T&lt;&gt;)</c> service type) are skipped
    /// because the DI container resolves them lazily and replacing the implementation type would cause recursive
    /// resolution. Both keyed and non-keyed closed-generic registrations are decorated when running on .NET 8+.
    /// </para>
    /// </remarks>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateOpenGeneric(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Type openServiceType,
        global::System.Type openDecoratorType)
    {
        if (!openServiceType.IsGenericTypeDefinition)
            openServiceType = openServiceType.GetGenericTypeDefinition();

        if (!openDecoratorType.IsGenericTypeDefinition)
            openDecoratorType = openDecoratorType.GetGenericTypeDefinition();

        for (int i = 0; i < services.Count; i++)
        {
            var descriptor = services[i];
            var serviceType = descriptor.ServiceType;

            if (!serviceType.IsGenericType)
                continue;

            // skip truly open-generic descriptors; MS.DI forbids factory on open service types
            // and replacing the implementation type would cause recursive resolution.
            if (serviceType.IsGenericTypeDefinition)
                continue;

            if (serviceType.GetGenericTypeDefinition() != openServiceType)
                continue;

            var typeArgs = serviceType.GetGenericArguments();
            global::System.Type closedDecoratorType;
            try
            {
                closedDecoratorType = openDecoratorType.MakeGenericType(typeArgs);
            }
            catch (global::System.ArgumentException)
            {
                continue;
            }

#if NET8_0_OR_GREATER
            if (descriptor.IsKeyedService)
            {
                var originalKey = descriptor.ServiceKey;
                var innerKeyed = CreateInnerKeyedFactory(descriptor);
                var lifetime = descriptor.Lifetime;

                services[i] = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                    serviceType: serviceType,
                    serviceKey: originalKey,
                    factory: (sp, key) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, closedDecoratorType, innerKeyed(sp, key)),
                    lifetime: lifetime);

                continue;
            }
#endif

            var inner = CreateInnerFactory(descriptor);
            var nonKeyedLifetime = descriptor.Lifetime;

            services[i] = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                serviceType: serviceType,
                factory: sp => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, closedDecoratorType, inner(sp)),
                lifetime: nonKeyedLifetime);
        }

        return services;
    }

    private static bool IsKeyedDescriptor(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
    {
#if NET8_0_OR_GREATER
        return descriptor.IsKeyedService;
#else
        return false;
#endif
    }

    private static global::System.Func<global::System.IServiceProvider, object> CreateInnerFactory(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
    {
        if (descriptor.ImplementationInstance is object instance)
            return _ => instance;

        if (descriptor.ImplementationFactory is global::System.Func<global::System.IServiceProvider, object> factory)
            return factory;

        var implementationType = descriptor.ImplementationType ?? descriptor.ServiceType;
        return sp => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, implementationType);
    }

#if NET8_0_OR_GREATER
    private static global::System.Func<global::System.IServiceProvider, object?, object> CreateInnerKeyedFactory(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
    {
        if (descriptor.KeyedImplementationInstance is object keyedInstance)
            return (_, _) => keyedInstance;

        if (descriptor.KeyedImplementationFactory is global::System.Func<global::System.IServiceProvider, object?, object> keyedFactory)
            return keyedFactory;

        var implementationType = descriptor.KeyedImplementationType ?? descriptor.ServiceType;
        return (sp, _) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, implementationType);
    }
#endif

}
