// <auto-generated />
#nullable enable

using System;

namespace Injectio.Extensions
{
    /// <summary>
    /// Provides extension methods for decorating registered services in an <see cref="global::Microsoft.Extensions.DependencyInjection.IServiceCollection"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The <b>Decorator pattern</b> wraps an existing service with additional behavior without modifying the
    /// original implementation. Each decorator implements the same interface as the service it wraps, creating
    /// a chain of responsibility:
    /// </para>
    /// <para>
    /// These methods work by replacing the <see cref="global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor"/>
    /// in-place within the service collection. The original factory, instance, or implementation type is captured
    /// so the inner service can still be resolved. The replacement descriptor preserves the original lifetime.
    /// Calling a decoration method multiple times stacks decorators, with the last call becoming the outermost layer.
    /// </para>
    /// <para><b>Usage example — decorating with a factory:</b></para>
    /// <code>
    /// // Register the original service
    /// services.AddScoped&lt;INotificationService, EmailNotificationService&gt;();
    ///
    /// // Decorate with logging
    /// services.Decorate&lt;INotificationService&gt;(
    ///     (sp, inner) =&gt; new LoggingNotificationService(inner, sp.GetRequiredService&lt;ILogger&gt;()));
    ///
    /// // Decorate with retry (stacks on top of logging)
    /// services.Decorate&lt;INotificationService&gt;(
    ///     (sp, inner) =&gt; new RetryNotificationService(inner));
    ///
    /// // Resolution chain: Retry → Logging → Email
    /// </code>
    /// <para><b>Usage example — decorating open generics:</b></para>
    /// <code>
    /// // Register closed-generic implementations
    /// services.AddScoped&lt;IRepository&lt;Order&gt;, OrderRepository&gt;();
    /// services.AddScoped&lt;IRepository&lt;Customer&gt;, CustomerRepository&gt;();
    ///
    /// // Decorate all IRepository&lt;T&gt; with caching
    /// services.DecorateOpenGeneric(
    ///     typeof(IRepository&lt;&gt;), typeof(CachingRepository&lt;&gt;));
    /// </code>
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class DecorationExtensions
    {
        /// <summary>
        /// Decorates all non-keyed registrations matching <paramref name="serviceType"/> by wrapping each resolved instance
        /// with <paramref name="decoratorFactory"/>.
        /// </summary>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <param name="serviceType">The service type to decorate.</param>
        /// <param name="decoratorFactory">A factory that receives the service provider and the original instance, and returns the decorated instance.</param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// This method replaces matching <see cref="global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor"/> entries in-place,
        /// preserving each registration lifetime. Keyed registrations are skipped.
        /// </para>
        /// <para>
        /// Multiple calls stack decorators, with the most recent decoration becoming the outermost layer.
        /// </para>
        /// </remarks>
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection Decorate(
            this Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            System.Type serviceType,
            System.Func<System.IServiceProvider, object, object> decoratorFactory)
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            if (serviceType is null)
                throw new global::System.ArgumentNullException(nameof(serviceType));

            if (decoratorFactory is null)
                throw new global::System.ArgumentNullException(nameof(decoratorFactory));

            int count = services.Count;

            for (int i = 0; i < count; i++)
            {
                var descriptor = services[i];

                if (descriptor.ServiceType != serviceType)
                    continue;

#if NET8_0_OR_GREATER
                if (descriptor.IsKeyedService)
                    continue;
#endif

                var innerFactory = CreateInnerFactory(descriptor, decoratorFactory);
                var lifetime = descriptor.Lifetime;

                Microsoft.Extensions.DependencyInjection.ServiceDescriptor serviceDescriptor = new(
                    serviceType: serviceType,
                    factory: innerFactory,
                    lifetime: lifetime
                );

                services[i] = serviceDescriptor;
            }

            return services;
        }

        /// <summary>
        /// Decorates all registrations of <typeparamref name="TService"/> by wrapping each resolved instance with <paramref name="decoratorFactory"/>.
        /// Keyed service registrations are skipped.
        /// </summary>
        /// <typeparam name="TService">The service type to decorate.</typeparam>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <param name="decoratorFactory">A factory that receives the service provider and the original instance, and returns the decorated instance.</param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// Decoration replaces each existing <see cref="global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor"/> for
        /// <typeparamref name="TService"/> in-place. The original descriptor's factory, instance, or implementation type is
        /// captured and used to resolve the inner service, which is then passed to <paramref name="decoratorFactory"/>.
        /// The replacement descriptor preserves the original registration's lifetime.
        /// </para>
        /// <para>
        /// Multiple calls stack: each call wraps whatever factory is currently registered, enabling layered decoration.
        /// Only non-keyed registrations are affected; use <c>DecorateKeyed</c> for keyed services.
        /// </para>
        /// </remarks>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Decorate<TService>(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::System.Func<global::System.IServiceProvider, TService, TService> decoratorFactory)
            where TService : class
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            if (decoratorFactory is null)
                throw new global::System.ArgumentNullException(nameof(decoratorFactory));

            var serviceType = typeof(TService);

            return services.Decorate(
                serviceType: serviceType,
                decoratorFactory: (sp, inner) => decoratorFactory(sp, (TService)inner)
            );
        }

        /// <summary>
        /// Decorates all registrations of <typeparamref name="TService"/> by wrapping each resolved instance
        /// with an automatically constructed instance of <typeparamref name="TDecorator"/>.
        /// Keyed service registrations are skipped.
        /// </summary>
        /// <typeparam name="TService">The service type to decorate.</typeparam>
        /// <typeparam name="TDecorator">The decorator type. Its constructor must accept a <typeparamref name="TService"/> parameter for the inner service; additional parameters are resolved from the service provider.</typeparam>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// This overload uses <see cref="global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance"/>
        /// to construct the decorator, passing the inner service instance as an explicit argument. Any remaining
        /// constructor parameters are resolved from the <see cref="global::System.IServiceProvider"/>.
        /// </para>
        /// </remarks>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Decorate<TService,
#if NET5_0_OR_GREATER
            [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
#endif
            TDecorator>(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
            where TService : class
            where TDecorator : class, TService
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            var serviceType = typeof(TService);

            return services.Decorate(
                serviceType: serviceType,
                decoratorFactory: static (sp, inner)
                    => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<TDecorator>(sp, inner)
            );
        }

#if NET8_0_OR_GREATER
        /// <summary>
        /// Decorates keyed registrations matching <paramref name="serviceType"/> and <paramref name="serviceKey"/>
        /// by wrapping each resolved instance with <paramref name="decoratorFactory"/>.
        /// </summary>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <param name="serviceType">The service type to decorate.</param>
        /// <param name="serviceKey">The key to match, or <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> for all keys.</param>
        /// <param name="decoratorFactory">A factory that receives the service provider, the key, and the original instance, and returns the decorated instance.</param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// This method only processes keyed registrations and preserves both the original key and lifetime for each replacement descriptor.
        /// </para>
        /// <para>
        /// Non-keyed registrations are skipped. Multiple calls stack decorators for matching keyed registrations.
        /// </para>
        /// </remarks>
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateKeyed(
            this Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            Type serviceType,
            object? serviceKey,
            Func<IServiceProvider, object?, object, object> decoratorFactory)
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            if (serviceType is null)
                throw new global::System.ArgumentNullException(nameof(serviceType));

            if (decoratorFactory is null)
                throw new global::System.ArgumentNullException(nameof(decoratorFactory));

            var anyKey = ReferenceEquals(serviceKey, global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey);
            var count = services.Count;

            for (int i = 0; i < count; i++)
            {
                var descriptor = services[i];

                if (descriptor.ServiceType != serviceType)
                    continue;

                if (!descriptor.IsKeyedService)
                    continue;

                var originalKey = descriptor.ServiceKey;
                var lifetime = descriptor.Lifetime;
                var isKeyMatch = global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(originalKey, serviceKey);

                if (!anyKey && !isKeyMatch)
                    continue;

                var innerFactory = CreateInnerFactoryKeyed(descriptor, decoratorFactory);

                Microsoft.Extensions.DependencyInjection.ServiceDescriptor serviceDescriptor = new(
                    serviceType: serviceType,
                    serviceKey: originalKey,
                    factory: innerFactory,
                    lifetime: lifetime
                );

                services[i] = serviceDescriptor;
            }

            return services;
        }

        /// <summary>
        /// Decorates all keyed registrations of <typeparamref name="TService"/> matching <paramref name="serviceKey"/>
        /// by wrapping each resolved instance with <paramref name="decoratorFactory"/>.
        /// Pass <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> to match all keys.
        /// </summary>
        /// <typeparam name="TService">The service type to decorate.</typeparam>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <param name="serviceKey">The key to match, or <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> for all keys.</param>
        /// <param name="decoratorFactory">A factory that receives the service provider, the key, and the original instance, and returns the decorated instance.</param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// This method iterates through all service descriptors for <typeparamref name="TService"/> and replaces each
        /// keyed registration whose key matches <paramref name="serviceKey"/>. The original keyed factory, instance,
        /// or implementation type is captured and used to resolve the inner service, which is then passed to
        /// <paramref name="decoratorFactory"/> along with the service provider and key. The replacement descriptor
        /// preserves the original registration's lifetime and key.
        /// </para>
        /// <para>
        /// Non-keyed registrations are skipped; use <c>Decorate</c> for those. Multiple calls stack, enabling
        /// layered decoration of keyed services.
        /// </para>
        /// </remarks>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateKeyed<TService>(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            object? serviceKey,
            global::System.Func<global::System.IServiceProvider, object?, TService, TService> decoratorFactory)
            where TService : class
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            if (decoratorFactory is null)
                throw new global::System.ArgumentNullException(nameof(decoratorFactory));

            var serviceType = typeof(TService);

            return services.DecorateKeyed(
                serviceType: serviceType,
                serviceKey: serviceKey,
                decoratorFactory: (sp, key, inner) => decoratorFactory(sp, key, (TService)inner)
            );
        }

        /// <summary>
        /// Decorates all keyed registrations of <typeparamref name="TService"/> matching <paramref name="serviceKey"/>
        /// by wrapping each resolved instance with an automatically constructed instance of <typeparamref name="TDecorator"/>.
        /// Pass <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> to match all keys.
        /// </summary>
        /// <typeparam name="TService">The service type to decorate.</typeparam>
        /// <typeparam name="TDecorator">The decorator type. Its constructor must accept a <typeparamref name="TService"/> parameter for the inner service; additional parameters are resolved from the service provider.</typeparam>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <param name="serviceKey">The key to match, or <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> for all keys.</param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// This overload uses <see cref="global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance"/>
        /// to construct the decorator, passing the inner service instance as an explicit argument. Any remaining
        /// constructor parameters are resolved from the <see cref="global::System.IServiceProvider"/>.
        /// </para>
        /// </remarks>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateKeyed<TService,
            [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]TDecorator>(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            object? serviceKey)
            where TService : class
            where TDecorator : class, TService
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            var serviceType = typeof(TService);

            return services.DecorateKeyed(
                serviceType: serviceType,
                serviceKey: serviceKey,
                decoratorFactory: static (sp, _, inner)
                    => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<TDecorator>(sp, inner)
            );
        }
#endif

        /// <summary>
        /// Decorates all closed-generic registrations whose generic type definition matches <paramref name="openServiceType"/>
        /// by wrapping each resolved instance with an instance of <paramref name="openDecoratorType"/>.
        /// </summary>
        /// <param name="services">The service collection containing the registrations to decorate.</param>
        /// <param name="openServiceType">The open generic service type (e.g., <c>typeof(IRepository&lt;&gt;)</c>).</param>
        /// <param name="openDecoratorType">The open generic decorator type that wraps the original service.</param>
        /// <param name="serviceKey">
        /// The key of the keyed registrations to decorate. Pass <see langword="null"/> to decorate non-keyed registrations,
        /// or <see cref="global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/> to decorate all keyed registrations.
        /// Keyed registration matching is only available on .NET 8 and later.
        /// </param>
        /// <returns>The same <paramref name="services"/> instance for chaining.</returns>
        /// <remarks>
        /// <para>
        /// This method scans all service descriptors for closed-generic types whose generic type definition matches
        /// <paramref name="openServiceType"/>. For each match, it closes <paramref name="openDecoratorType"/> over the
        /// same type arguments and replaces the descriptor with a factory that resolves the original service and passes
        /// it to <see cref="global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance"/>.
        /// The replacement descriptor preserves the original registration's lifetime.
        /// </para>
        /// <para>
        /// Open-generic descriptors (those registered with an open <c>typeof(T&lt;&gt;)</c> service type) are skipped
        /// because the DI container resolves them lazily and replacing the implementation type would cause recursive
        /// resolution. When <paramref name="serviceKey"/> is <see langword="null"/>, keyed registrations are skipped.
        /// When <paramref name="serviceKey"/> is non-null on .NET 8 and later, non-keyed registrations are skipped and
        /// only keyed registrations with the matching key are decorated.
        /// </para>
        /// </remarks>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Closing an open generic decorator type at runtime requires dynamic code generation.")]
#endif
#if NET5_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Closing an open generic decorator type at runtime can require constructors that are not statically visible to the trimmer.")]
#endif
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection DecorateOpenGeneric(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::System.Type openServiceType,
            global::System.Type openDecoratorType,
            object? serviceKey = null)
        {
            if (services is null)
                throw new global::System.ArgumentNullException(nameof(services));

            if (openServiceType is null)
                throw new global::System.ArgumentNullException(nameof(openServiceType));

            if (openDecoratorType is null)
                throw new global::System.ArgumentNullException(nameof(openDecoratorType));

            if (!openServiceType.IsGenericTypeDefinition)
                openServiceType = openServiceType.GetGenericTypeDefinition();

            if (!openDecoratorType.IsGenericTypeDefinition)
                openDecoratorType = openDecoratorType.GetGenericTypeDefinition();

#if NET8_0_OR_GREATER
            var anyKey = ReferenceEquals(serviceKey, global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey);
#else
            _ = serviceKey;
#endif

            int count = services.Count;
            for (int i = 0; i < count; i++)
            {
                var descriptor = services[i];
                var serviceType = descriptor.ServiceType;

                // Only closed generic registrations can be rewritten safely.
                if (!serviceType.IsGenericType)
                    continue;

                // skip truly open-generic descriptors; MS.DI forbids factory on open service types
                // and replacing the implementation type would cause recursive resolution.
                if (serviceType.IsGenericTypeDefinition)
                    continue;

                if (serviceType.GetGenericTypeDefinition() != openServiceType)
                    continue;

                var typeArgs = serviceType.GetGenericArguments();
                global::System.Type closedDecoratorType;
                try
                {
                    // Close the open decorator over the current service type arguments.
                    closedDecoratorType = openDecoratorType.MakeGenericType(typeArgs);
                }
                catch (global::System.ArgumentException)
                {
                    // Skip incompatible generic argument combinations.
                    continue;
                }

                var lifetime = descriptor.Lifetime;

#if NET8_0_OR_GREATER
                if (descriptor.IsKeyedService)
                {
                    var originalKey = descriptor.ServiceKey;

                    if (!anyKey && !global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(originalKey, serviceKey))
                        continue;

                    var innerFactory = CreateInnerFactoryKeyed(
                        descriptor: descriptor,
                        decoratorFactory: (sp, _, inner)
                            => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, closedDecoratorType, inner)
                    );

                    services[i] = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                        serviceType: serviceType,
                        serviceKey: originalKey,
                        factory: innerFactory,
                        lifetime: lifetime
                    );

                    continue;
                }

                if (serviceKey is not null)
                    continue;
#endif

                var factory = CreateInnerFactory(
                    descriptor: descriptor,
                    decoratorFactory: (sp, inner)
                        => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, closedDecoratorType, inner)
                );

                services[i] = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                    serviceType: serviceType,
                    factory: factory,
                    lifetime: lifetime);
            }

            return services;
        }

        private static Func<IServiceProvider, object> CreateInnerFactory(
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor,
            System.Func<System.IServiceProvider, object, object> decoratorFactory)
        {
            if (descriptor.ImplementationInstance is object instance)
                return sp => decoratorFactory(sp, instance);

            if (descriptor.ImplementationFactory is global::System.Func<global::System.IServiceProvider, object> factory)
                return sp => decoratorFactory(sp, factory(sp));

            var implementationType = descriptor.ImplementationType;
            if (implementationType is null)
                throw new global::System.InvalidOperationException("The service descriptor does not provide an implementation type, factory, or instance.");

            return sp => decoratorFactory(sp, global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, implementationType));
        }

#if NET8_0_OR_GREATER
        private static Func<IServiceProvider, object?, object> CreateInnerFactoryKeyed(
            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor,
            System.Func<System.IServiceProvider, object?, object, object> decoratorFactory)
        {
            var originalKey = descriptor.ServiceKey;

            if (descriptor.KeyedImplementationInstance is object keyedInstance)
                return (sp, key) => decoratorFactory(sp, key, keyedInstance);

            if (descriptor.KeyedImplementationFactory is global::System.Func<global::System.IServiceProvider, object?, object> keyedFactory)
                return (sp, key) => decoratorFactory(sp, key, keyedFactory(sp, key));

            var implementationType = descriptor.KeyedImplementationType;
            if (implementationType is null)
                throw new global::System.InvalidOperationException("The keyed service descriptor does not provide an implementation type, factory, or instance.");

            return (sp, key) => decoratorFactory(sp, key, global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(sp, implementationType));
        }
#endif
    }
}
